MONEY = 'Введите сумму, которую вы готовы потратить на подарок'

SIZE = 'Выберите размер букета:'
POSSIBLE_SIZES = 'Возможные размеры букетов, согласно вашему бюджету:'
TYPE_BOUQUET = 'Выберите тип композиции:'
BUNCH_OF_FLOWERS = 'монобукет'
BOUQUET_OF_FLOWERS = 'сборный букет'

JEWELRY = 'Вам представлены категории из раздела "Украшения"'
CATEGORY_JEWELRY = 'Укажите категорию товара'
RINGS = 'Кольца'
BRASLETS = 'Браслеты'
NECKLACES = 'Колье'
CATEGORY_RINGS = 'Выберите подходящий вариант кольца'
RNG_WENZEL = 'Кольцо-вензель'
RNG_FINGER = 'Перстень'
RNG_ENGAGEMENT = 'Помолвочное кольцо'
CATEGORY_BRASLETS = 'Выберите подходящий вариант браслета'
BRASLET_THN = 'Тонкий браслет'
BRASLET_WCKR = 'Плетеный браслет'
BRASLET_CHN = 'Цепной браслет'
CATEGORY_NECKLACE = 'Выберите подходящий вариант колье'
NECKLACE_CHKER = 'Чокер'
NECKLACE_KOLLAR = 'Коллар'
NECKLACE_PRINCES = 'Принцесса'


DESSERT_CATEGORY = 'Выберите категорию десерта:'
CAKES = 'Тортики'
CAPCAKES = 'Капкейки'
CANDIES = 'Конфеты'

RIGHT = 'В яблочко!'
WRONG = 'Аня хотела другой подарок'
