MONEY = 'Введите сумму, которую вы готовы потратить на подарок'
CATEGORY = 'Укажите категорию товара'
VARIANT = 'Выберите подходящий вариант подарка'
RIGHT = 'В яблочко!'
WRONG = 'Аня хотела другой подарок'

SIZE = 'Выберите размер букета:'
POSSIBLE_SIZES = 'Возможные размеры букетов, согласно вашему бюджету:'
TYPE_BOUQUET = 'Выберите тип композиции:'
BUNCH_OF_FLOWERS = 'монобукет'
BOUQUET_OF_FLOWERS = 'сборный букет'

JEWELRY = 'Вам представлены категории из раздела "Украшения"'
RINGS = 'Кольца'
BRASLETS = 'Браслеты'
NECKLACES = 'Колье'
RNG_WENZEL = 'Кольцо-вензель'
RNG_FINGER = 'Перстень'
RNG_ENGAGEMENT = 'Помолвочное кольцо'
BRASLET_THN = 'Тонкий браслет'
BRASLET_WCKR = 'Плетеный браслет'
BRASLET_CHN = 'Цепной браслет'
NECKLACE_CHKER = 'Чокер'
NECKLACE_KOLLAR = 'Коллар'
NECKLACE_PRINCES = 'Принцесса'

CAKES = 'Тортики'
CAPCAKES = 'Капкейки'
CANDIES = 'Конфеты'
